### ISSUE TITLE
Does not work on circular/round only objects.

### ISSUE THREAD

**Issue by VoronMods** [Finn2708/CounterboreBridging#1]
great plug-in to save time, did it always manual and wonder why this is not a function. Thanks.

I found a issue that you need a straight edge for this to be working, won't on a just circular objects w/o adding or modifying it.
Is there a way to add  a function to avoid this? I did try to add a line in sketch, no luck. Always needs edge of a solid.

**Comment by Finn2708** [comment]
Thanks for the feedback. The `Direction` input is used to define the orientation of the primary bridging. While the tool could default to horizontal or vertical alignment, I personally prefer more control over the process.
Currently, the `Direction` input has a selection filter applied, only allowing edges of solid bodies as inputs. I will look into adding sketch edges to that filter.

**Comment by Finn2708** [comment]
This should be fixed in 6d95249. The `Direction` input will now accept edges of bodies, lines of sketches and construction lines, e.g. origin axes.

Closing this for now. If you run into other problems, please let me know :)

**Comment by VoronMods** [comment]
Excellent, works perfect with sketch line and origin axis, don't even need to create sketch like, origin axis is enough, Thanks.
