### ISSUE TITLE
Suggestion: Linking Parameters to Layer height

### ISSUE THREAD

**Issue by AdamV3D** [Finn2708/CounterboreBridging#2]
Fantastic plugin, so glad it exists!

I have just one suggestion, enable linking of layer height to a model parameter.

What I did.

1. Create model with counterbore
2. create "layerheight" parameter
3. start counterbore bridging tool.
4. Select face, select edge, enter "layerheight" in the layer height field.
5. Counterbore correctly created with correct layer height.
6. Change the layerheight parameter

What I expected:
counterbore bridge depth changes height to match the new parameter value.

What i got:
counterbore bridge depth stays at the original layer height.

Workaround:
Edit each extrude feature and re-link it to the layerheight parameter. (obviously this is pretty slow to do)

**Comment by Finn2708** [comment]
Thanks for the feedback. 
I will look into fixing this!

**Comment by AdamV3D** [comment]
Great, thankyou for all your hard work.
I wanted to tag this as feature request as it's not really an 'issue' but it wouldn't let me, so here we are.

**Comment by Finn2708** [comment]
No worries. I would have expected this to work, but never bothered to check. 

Anyway, should be fixed now in [2586671](https://github.com/Finn2708/CounterboreBridging/commit/258667144da8adb0f8f577d4f292d14e6b0a8a03). 

Let me know if you run into any other issues :)
