### ISSUE TITLE
doesn't show up in Fusion

### ISSUE THREAD

**Issue by dragoonmc** [Finn2708/CounterboreBridging#3]
Hey, Just wanted to let you know that with how Github downloads a repository it adds "-main" to the top folder name and this prevents Fusion from importing the addin.
You may want to put a note bout this in the readme

**Comment by Finn2708** [comment]
Thanks for the feedback. I was not able to reproduce this on Windows 11 using git's CLI in powershell or gitbash using these commands:
```
# SSH
git clone git@github.com:Finn2708/CounterboreBridging.git
git clone -b main git@github.com:Finn2708/CounterboreBridging.git

# HTTPS
git clone https://github.com/Finn2708/CounterboreBridging.git
git clone -b main https://github.com/Finn2708/CounterboreBridging.git
```
Could you provide more details how you got this result?

**Comment by dragoonmc** [comment]
Sorry for not being clear. I literally downloaded zip using Chrome. I'm not all that savy with Github so I do the simple ways
![image](https://github.com/Finn2708/CounterboreBridging/assets/22428895/dba870dc-83d8-4419-bd12-797916b8b41e)

**Comment by Finn2708** [comment]
Ah, okay. Everyone works a little different, I guess.
I added a short hint to the installation instructions, so people with a similar workflow have it a little easier. 

Let me know if you run into any other issues :)
