### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by TheSin-** [Finn2708/CounterboreBridging#4]
I'm new to F360 addins so bear with me.

```
Counterbore Bridging Command Execute Event
 ===== Error =====
 CommandEventHandler
Traceback (most recent call last):
  File "/Users/justin/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/CounterboreBridging/lib/fusion360utils/event_utils.py", line 84, in notify
    callback(args)
  File "/Users/justin/Library/Application Support/Autodesk/Autodesk Fusion 360/API/AddIns/CounterboreBridging/commands/counterboreBridgingDialog/entry.py", line 143, in command_execute
    inner = circles[1]
            ~~~~~~~^^^
IndexError: list index out of range

 Counterbore Bridging Command Destroy Event
```

Since I"m only selecting the circle face which I assume is in circles[0] what should circles[1] be and why don't I hav one?

**Comment by TheSin-** [comment]
I figured it out, there was a bore too close that caused the putter edge to not be a proper circle

**Comment by Finn2708** [comment]
The tool expects you to select the counterbored face. From that face, two circles are selected: `circles[0]` is the outer edge of the face, `circles[1]` is the inner. I think you may have selected the wrong input face, so there was no inner edge. 

Glad you figured it out. The error handling could probably be improved a bit...

**Comment by TheSin-** [comment]
Naw it works great! Just if the edge has a cut in it it won’t work. That was my issue.  And it won’t work on hexes obviously since it’s not a circle :)

but for what it is meant for it works great.  I was happy to have it, thank you!
